### ISSUE TITLE
Add a more efficient way to initialize a new browser-env

### ISSUE THREAD

**Issue by gajus** [lukechilds/browser-env#26] opened 2016-11-22 12:50 UTC
I am using `setupBrowserEnv` in `beforeEach` in my ava test suite.

```js
import browserEnv from 'browser-env';

export const setupBrowserEnv = () => {
  delete global.window;
  delete global.pbjs;

  browserEnv([
    'window',
    'document',
    'navigator'
  ]);

  // Some of the scripts assume presence of a <script> tag in the document.
  const scriptElement = document.createElement('script');

  document.body.appendChild(scriptElement);
};

```

The problem is that it is taking 475ms to initialise.

Is there no way to clone and re-use jsdom created objects after they have been created once?

**Comment by lukechilds** [comment] 2016-11-22 14:16
Yeah we could save the `jsdom` instance on first init and recycle that. The issue is then if you modify any of the `jsdom` references in a test any later tests will have those modified references which would be bad.

When `browser-env` is called it should create a brand new environment.

**Comment by lukechilds** [comment] 2016-11-22 14:20
In fact we could maybe save the `jsdom` instance and then return copies of that reference each time `browser-env` is called. That way we only have to wait for the heavy `jsdom` stuff once and and there shouldn't be any shared reference issues.

I'm happy to look into implementing this but I'm currently traveling round Thailand and won't have reliable computer/internet access for a few weeks.

**Comment by lukechilds** [comment] 2016-12-09 14:45
@gajus Taken a look into this and I don't seem to be able to clone the main `jsdom` object without mangling it. Also not sure this is a good idea, speeding up `browser-env` would be great but the main focus is to return reliable results as it's main use is for tests.

If you need multiple browser instances and want to reduce startup time you could try splitting your tests out into multiple tests files. AVA should run these in parallel as separate processes so the browser globals don't conflict.

Gonna close this, thanks for taking the time to submit 👍

**Closed by lukechilds** 2016-12-09 14:45 UTC
